<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Farm extends Model
{

    public $fillable = ['stt',
                        'code',
                        'ho_va_ten',
                        'chuc_vu',
                        'bo_phan',
                        //'ngay_vao',
                        //'ngay_ky_hop_dong',
                        'email',
                        'phan_loai_nv',
                        //'luong_thu_viec',
                        'luong_vi_tri_nang_luc',
                        'thuong_kpi',
                        //'phu_cap_thue_nha',
                        'thuong_nang_suat',
                        'phu_cap_di_lai',
                        'phu_cap_an',
                        'phu_cap_dien_thoai',
                        //'cong_tac_phi',
                        'kiem_nhiem',
                        'ho_tro_chua_thuong',
                        //'thuong_phong_dich',
                        //'ho_tro_khac',
                        'tong_luong_thoa_thuan',
                        'ngay_cong_thuc_te',
                        'nghi_phep',
                        'nghi_le',
                        'truc_tet',
                        'tong_cong',
                        'luong_theo_ngay_cong',
                        'luong_200',
                        'cong_ca_dem',
                        'luong_cong_them',
                        //'thuong_kpi_thuc_te',
                        'tong_luong_chinh',
                        //'thue_nha',
                        'thuong_kpi_thuc_te',
                        'tien_thuong_nang_suat',
                        'di_lai',
                        'tien_an',
                        'dien_thoai',
                        'tien_kiem_nhiem',
                        //'cong_tac_phi_thuc_te',
                        //'phong_dich',
                        'tien_ho_tro_chua_thuong',
                        //'ho_tro_khac_thuc_te',
                        'tong_phu_cap_tro_cap',
                        'gio_truc_trua',
                        'gio_tang_ca_150',
                        'gio_tang_ca_180',
                        'gio_tang_ca_300',
                        'tong_gio_tang_ca',
                        'tien_truc_trua',
                        'tien_tang_ca_150',
                        'tien_tang_ca_180',
                        'tien_tang_ca_300',
                        'tong_tien_tang_ca',
                        'khoan_bu_tru_khac',
                        'tong_thu_nhap',
                        'thu_nhap_chiu_thue',
                        'muc_dong',
                        'thu_bao_hiem',
                        'so_npt',
                        'tong_gtgc',
                        'tong_cac_khoan_giam_tru',
                        'thu_nhap_tinh_thue',
                        'thue_phai_nop',
                        'doan_phi_nld',
                        'thuc_linh',
                        'bhxh',
                        'doan_phi_cty',
                        'tong_phi_cty',
                        'so_tai_khoan',
    ];

}